# Generated by Django 5.1.7 on 2025-03-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0003_electeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='electeur',
            field=models.ManyToManyField(related_name='Electeur_list', to='rfid_app.electeur'),
        ),
    ]
