# Generated by Django 5.1.7 on 2025-03-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0004_electeur_token_election_electeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='electeur',
            new_name='electeurs',
        ),
    ]
