# Generated by Django 5.1.7 on 2025-03-19 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
