# Generated by Django 5.1.7 on 2025-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0007_election_date_cloture_alter_election_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='electeurs_votants',
            field=models.ManyToManyField(blank=True, related_name='electeur_votants', to='rfid_app.electeur'),
        ),
    ]
