# Generated by Django 5.1.7 on 2025-03-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0008_election_electeurs_votants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='electeurs_votants',
        ),
    ]
