# Generated by Django 5.1.7 on 2025-03-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0009_remove_election_electeurs_votants'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
