# Generated by Django 5.1.7 on 2025-03-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0010_election_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='token_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
