# Generated by Django 5.1.7 on 2025-04-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0011_electeur_token_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='election',
        ),
    ]
